# All the SQLite files and metadata.csv are generated by
# a Snakemake workflow (lrbase-workflow)
# https://github.com/rikenbit/lrbase-workflow

# All the SQLite files are finally saved in the sqlite/ directory.

# To generate Ligand Gene ID - Receptor Gene ID correspondance table
# of 134 species,
# highly loaded calculations such as

# download 127GB of UniProtKB (TREMBL) data,
# and assigning human Ligand-Receptor pairs
# to other species based on sequence homology.
# are required.

# Hence using distributed computing environment such as
# Open Grid Engine or Slurm is highly recommended.

# For the details, see the README.md and workflow/*.smk of lrbase-workflow
